version: 0.2
phases:
  install:
    commands:
      - echo "install phase..."
      - apk -Uuv add groff less python py-pip
      - pip install awscli
  pre_build:
    commands:
      - echo "pre_build phase..."
      - yarn -v
      - node -v
  build:
    commands:
      - echo "Running build..."
      - sh scripts/build.sh
  post_build:
    commands:
      - echo "Nothing to do in post_build phase..."
