version: 0.2
phases:
  install:
    commands:
      - echo "install phase..."
      - yarn -v
      - node -v
  pre_build:
    commands:
      - echo "Nothing to do in pre_build phase..."
  build:
    commands:
      - echo "Running build..."
      - sh scripts/build.sh
  post_build:
    commands:
      - echo "Nothing to do in post_build phase..."
